// Messaging module — bilingual UI strings. (Conversations/messages come from Supabase.)
export const MESSAGING_STRINGS = {
  chatsTitle: { de: 'Chats', en: 'Chats' },
  newMatches: { de: 'Neue Matches', en: 'New matches' },
  messages: { de: 'Nachrichten', en: 'Messages' },
  searchPh: { de: 'Suchen…', en: 'Search…' },
  emptyTitle: { de: 'Noch keine\nNachrichten', en: 'No messages\nyet' },
  emptySub: {
    de: 'Wenn du ein Match hast, beginnt hier eure Unterhaltung.',
    en: 'When you match, your conversation starts here.',
  },
  inputPh: { de: 'Nachricht schreiben…', en: 'Type a message…' },
  today: { de: 'Heute', en: 'Today' },
  online: { de: 'Online', en: 'Online' },
  lastSeen: { de: 'zuletzt aktiv vor kurzem', en: 'active recently' },
  typing: { de: 'schreibt…', en: 'typing…' },
  delivered: { de: 'Zugestellt', en: 'Delivered' },
  read: { de: 'Gelesen', en: 'Read' },
  viewProfile: { de: 'Profil ansehen', en: 'View profile' },
  block: { de: 'Blockieren', en: 'Block' },
  report: { de: 'Melden', en: 'Report' },
  unmatch: { de: 'Match auflösen', en: 'Unmatch' },
  cancel: { de: 'Abbrechen', en: 'Cancel' },
  blockTitle: { de: 'Nutzer blockieren?', en: 'Block user?' },
  blockBody: {
    de: 'Ihr seht euch nicht mehr und könnt nicht mehr schreiben.',
    en: 'You won’t see each other or be able to message anymore.',
  },
  reportTitle: { de: 'Nutzer melden?', en: 'Report user?' },
  reportBody: {
    de: 'Unser Team prüft die Meldung vertraulich.',
    en: 'Our team will review the report confidentially.',
  },
  confirm: { de: 'Bestätigen', en: 'Confirm' },
  imageSent: { de: 'Foto', en: 'Photo' },
};
