// Mock discovery profiles + religion options + default filters.
// Photos are remote (Unsplash) so no local binaries are required.
// `interests` and `religion` use the same keys as constants/profileSetup.js for filtering.

export const RELIGION_OPTIONS = [
  { key: 'christian', label: { de: 'Christlich', en: 'Christian' } },
  { key: 'muslim', label: { de: 'Muslimisch', en: 'Muslim' } },
  { key: 'jewish', label: { de: 'Jüdisch', en: 'Jewish' } },
  { key: 'hindu', label: { de: 'Hinduistisch', en: 'Hindu' } },
  { key: 'buddhist', label: { de: 'Buddhistisch', en: 'Buddhist' } },
  { key: 'spiritual', label: { de: 'Spirituell', en: 'Spiritual' } },
  { key: 'none', label: { de: 'Konfessionslos', en: 'Non‑religious' } },
  { key: 'other', label: { de: 'Andere', en: 'Other' } },
];

export const PROFILES = [
  {
    id: '1',
    name: 'Sophia',
    age: 27,
    distance: 5,
    city: 'München',
    country: 'de',
    job: 'Marketing Managerin',
    education: 'Master in BWL',
    height: 168,
    children: 'want',
    religion: 'christian',
    goal: 'serious',
    verified: true,
    bio: 'Ich liebe gutes Essen, spontane Roadtrips und tiefgründige Gespräche.',
    interests: ['travel', 'yoga', 'cooking', 'music'],
    photos: [
      'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=1600&q=90&fit=crop&crop=faces',
      'https://images.unsplash.com/photo-1488716820095-cbe80883c496?w=1600&q=90&fit=crop&crop=faces',
    ],
  },
  {
    id: '2',
    name: 'Mia',
    age: 24,
    distance: 2,
    city: 'Zürich',
    country: 'ch',
    job: 'Fotografin',
    education: 'Studium Fotografie',
    height: 170,
    children: 'open',
    religion: 'spiritual',
    goal: 'longterm',
    verified: true,
    bio: 'Ich fange goldene Stunden und gute Vibes ein ✨. Verrate mir deinen Lieblingsreiseort!',
    interests: ['travel', 'photography', 'yoga', 'nature'],
    photos: [
      'https://images.unsplash.com/photo-1496440737103-cd596325d314?w=1600&q=90&fit=crop&crop=faces',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=1600&q=90&fit=crop&crop=faces',
    ],
  },
  {
    id: '3',
    name: 'Emma',
    age: 27,
    distance: 4,
    city: 'München',
    country: 'de',
    job: 'Marketing Lead',
    education: 'Master Marketing',
    height: 172,
    children: 'want',
    religion: 'none',
    goal: 'serious',
    verified: false,
    bio: 'Pflanzensammlerin 🌿, Podcast-Süchtige und angehende Surferin. Auf der Suche nach einer echten Verbindung.',
    interests: ['nature', 'reading', 'travel', 'fitness'],
    photos: [
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=1600&q=90&fit=crop&crop=faces',
      'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=1600&q=90&fit=crop&crop=faces',
    ],
  },
  {
    id: '4',
    name: 'Lena',
    age: 29,
    distance: 8,
    city: 'Hamburg',
    country: 'de',
    job: 'Ärztin',
    education: 'Studium Medizin',
    height: 165,
    children: 'have',
    religion: 'christian',
    goal: 'marriage',
    verified: true,
    bio: 'Liebe lange Gespräche bei gutem Wein 🍷. Familie und Ehrlichkeit sind mir wichtig.',
    interests: ['wine', 'cooking', 'music', 'dancing'],
    photos: [
      'https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?w=1600&q=90&fit=crop&crop=faces',
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=1600&q=90&fit=crop&crop=faces',
    ],
  },
  {
    id: '5',
    name: 'Clara',
    age: 25,
    distance: 6,
    city: 'Basel',
    country: 'ch',
    job: 'Architektin',
    education: 'Master Architektur',
    height: 174,
    children: 'want',
    religion: 'spiritual',
    goal: 'longterm',
    verified: false,
    bio: 'Designverliebt, immer auf der Suche nach dem besten Croissant der Stadt 🥐.',
    interests: ['art', 'coffee', 'travel', 'foodie'],
    photos: [
      'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=1600&q=90&fit=crop&crop=faces',
      'https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?w=1600&q=90&fit=crop&crop=faces',
    ],
  },
  {
    id: '6',
    name: 'Hannah',
    age: 31,
    distance: 12,
    city: 'Wien',
    country: 'at',
    job: 'Musikerin',
    education: 'Musikhochschule',
    height: 169,
    children: 'open',
    religion: 'none',
    goal: 'serious',
    verified: true,
    bio: 'Gitarristin auf der Suche nach meinem Duett-Partner 🎸. Spontane Roadtrips willkommen.',
    interests: ['music', 'travel', 'coffee', 'movies'],
    photos: [
      'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=1600&q=90&fit=crop&crop=faces',
      'https://images.unsplash.com/photo-1485875437342-9b39470b3d95?w=1600&q=90&fit=crop&crop=faces',
    ],
  },
  {
    id: '7',
    name: 'Amira',
    age: 28,
    distance: 5,
    city: 'Frankfurt',
    country: 'de',
    job: 'Anwältin',
    education: 'Jura Staatsexamen',
    height: 167,
    children: 'want',
    religion: 'muslim',
    goal: 'marriage',
    verified: true,
    bio: 'Ehrgeizig, herzlich und immer für ein Abenteuer zu haben. Suche etwas Ernsthaftes.',
    interests: ['reading', 'foodie', 'fitness', 'travel'],
    photos: [
      'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=1600&q=90&fit=crop&crop=faces',
      'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=1600&q=90&fit=crop&crop=faces',
    ],
  },
  {
    id: '8',
    name: 'Julia',
    age: 23,
    distance: 9,
    city: 'Köln',
    country: 'de',
    job: 'Studentin',
    education: 'Bachelor (laufend)',
    height: 171,
    children: 'open',
    religion: 'christian',
    goal: 'longterm',
    verified: false,
    bio: 'Yoga am Morgen, Tanzen am Abend 💃. Das Leben ist zu kurz für schlechten Kaffee.',
    interests: ['yoga', 'dancing', 'coffee', 'nature'],
    photos: [
      'https://images.unsplash.com/photo-1502764613149-7f1d229e230f?w=1600&q=90&fit=crop&crop=faces',
      'https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?w=1600&q=90&fit=crop&crop=faces',
    ],
  },
];

export const DEFAULT_FILTERS = {
  ageMin: 18,
  ageMax: 45,
  distanceMax: 50, // km
  religion: [], // empty = any
  interests: [], // empty = any
};

export const AGE_BOUNDS = { min: 18, max: 80 };
export const DISTANCE_BOUNDS = { min: 1, max: 150 };
